steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - deploy/web.Dockerfile
      - --build-arg
      - NEXT_PUBLIC_ROVO_API_URL=$_API_URL
      - --build-arg
      - NEXT_PUBLIC_PRIVY_APP_ID=$_PRIVY_APP_ID
      - --build-arg
      - NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$_WALLETCONNECT_PROJECT_ID
      - --build-arg
      - NEXT_PUBLIC_ROBINHOOD_RPC_URL=$_RPC_URL
      - --build-arg
      - NEXT_PUBLIC_ROVO_REGISTRY_ADDRESS=$_REGISTRY
      - --build-arg
      - NEXT_PUBLIC_ROVO_FACTORY_WRAPPER_ADDRESS=$_WRAPPER
      - --build-arg
      - NEXT_PUBLIC_ROVO_ZAP_ROUTER_ADDRESS=$_ZAP
      - --build-arg
      - NEXT_PUBLIC_ROVO_SPLITTER_ADDRESS=$_SPLITTER
      - --build-arg
      - NEXT_PUBLIC_ROVO_NOTTINGHAM_ADDRESS=$_NOTTINGHAM
      - --build-arg
      - NEXT_PUBLIC_ROVO_HOLDER_REWARDS_ADDRESS=$_HOLDER_REWARDS
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/rovo/web:$BUILD_ID
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/rovo/web:$BUILD_ID
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - rovo-web
      - --project=$PROJECT_ID
      - --region=us-central1
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/rovo/web:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _API_URL: https://api.rovo.fun
  _PRIVY_APP_ID: cmuix6wbb00gd0cl9h290bx2s
  _WALLETCONNECT_PROJECT_ID: ""
  _RPC_URL: https://robinhood.drpc.org
  _REGISTRY: "0x9e6D6f8FCa32E721c24D7f668a6EA1dC896C8916"
  _WRAPPER: "0x5E952c8E7EB763d7d1CF318cba8ECF8259eF02da"
  _ZAP: "0x98ab554F40069521161B659E02Ffbe48CC4D1a79"
  _SPLITTER: "0xeF991a125b91dA6794d0D62137cF0A2e724ACc54"
  _NOTTINGHAM: "0x882f00222908C63a58B215aad202c6baBdF5d575"
  _HOLDER_REWARDS: "0x2A07cb48E7A1bBC6f7dbE1f7Ba06ADbE233a2911"
